version: "3"


services:
  influxdb:
    image: influxdb:1.8-alpine
    ports:
    - 8086:8086

  proxy:
    build: docker_images/proxy_service
    ports:
    - 5000:5000
    links:
      - influxdb
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - FLASK_PORT=5000
    depends_on:
      - influxdb

  payload_generator:
    build: docker_images/payload_generator
    depends_on:
      - influxdb
    environment:
      - TARGET_HOST=influxdb
      - TARGET_PORT=8086
    links:
      - influxdb
      - proxy

  grafana:
      image: grafana/grafana
      environment:
      - GF_SERVER_HTTP_PORT=8092
      ports:
      - 8092:8092
      links:
      - influxdb
      - proxy
