version: "3"


services:
  timescale:
    build: docker_images/timescale
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=postgres
    - POSTGRES_DB=laptop
    ports:
    - 5432:5432

  proxy:
    build: docker_images/proxy_service
    ports:
    - 5000:5000
    links:
      - timescale
    environment:
      - POSTGRES_HOST=timescale
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=laptop
      - FLASK_PORT=5000
    depends_on:
      - timescale

  payload_generator:
    build: docker_images/payload_generator
    depends_on:
      - influxdb
    environment:
      - TARGET_HOST=proxy
      - TARGET_PORT=5000
    links:
      - proxy

  grafana:
      image: grafana/grafana
      environment:
      - GF_SERVER_HTTP_PORT=8092
      ports:
      - 8092:8092
      links:
      - proxy
      - timescale
